version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=4000
      # Aquí asegúrate de tener la URI de Mongo Atlas en alguna variable o en config
      # - MONGODB_URI=mongodb+srv://usuario:pass@cluster0.mongodb.net/tu_db?retryWrites=true&w=majority
    depends_on: []

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PORT=5173
    depends_on:
      - backend