version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mern_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: mern_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern_db
      - NODE_ENV=production
    volumes:
      - ./datos:/app/datos
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: mern_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
